version: '3'
services:
  tor:
    build: .
    container_name: torproxy
    restart: always
    ports:
      - "9050:9050"  # Expose the SOCKS proxy
      - "9051:9051"  # Expose the ControlPort for IP rotation
    environment:
      - TOR_SOCKS_PORT=9050
    command: tor
